### PR TITLE
IoT Ticket client

### PR DESCRIPTION
**Pull request by Andriamanitra**
Implemented a client to send data to the IoT Ticket. Error handling and logging are not ideal but I think we can merge this and work on those later if needed. It would be relatively easy to get rid of the iotticket dependency (its implementation is not the greatest and I'm not sure if it's even maintained) but this works well enough for now.

### CODE REVIEW

**Comment by niladricts** [comment]
@Andriamanitra why init.py is pushed although it is empty. It will be better if you give a sample of the response as a comment in the client.py. Please note handling error responses with only showing messages is not enough, we need to do something with this. Either continue the process after error handling or stop it. So, it should be there clearly in the code.

**Comment by Andriamanitra** [comment]
> why init.py is pushed although it is empty

`__init__.py` has a special meaning in Python, it is used to make a directory into a [package](https://docs.python.org/3/tutorial/modules.html#packages). In practice it allows [this line (in object_detector branch)](https://github.com/niladricts/BusinessTampereTrafficMonitoring/blob/object_detector/setup.py#L8) to find the package and install it when running `pip install .` in the root directory of the project.

> It will be better if you give a sample of the response as a comment in the client.py.

We don't need the response for anything – I only left the comment about it because the special case where `"All datanodes are not valid"` is returned could conceivably be considered an error, so anyone modifying the method in the future should be aware of the odd behavior.

> Please note handling error responses with only showing messages is not enough, we need to do something with this. Either continue the process after error handling or stop it. So, it should be there clearly in the code.

What kind of processing? The whole system shouldn't stop on a single network error. I guess we could retry once, and only then discard the data point? Do you think that would be suitable? I don't think losing some data points when network is down (in which case retrying wouldn't help) or requests fail for another reason (which _should_ be rare) is a big deal, but I am listening for any suggestions you may have to make it more robust.

**Comment by niladricts** [comment]
I meant to say after error handling, there should be a step to continue the process of calling the IoT client or stopping it. Retry would be better but not more than 3 times with a gap of 3-5 ms.

**Comment by niladricts** [comment]
I am merging this request. @Andriamanitra, if any refactoring is needed, you can add those lines later.

**Pull request merged**
