### PR TITLE
Added an addition logger.error() line and logging of stderr's. 

### PR DESCRIPTION
**Pull request by lassijjk**
Also modified the reinitialization a little bit.

### CODE REVIEW

**Comment by lassijjk** [comment]
Oh I forgot to run pre-commit locally. Dang.

**Comment by Andriamanitra** [comment]
If you try to run this piece of code you'll get `ValueError: task_done() called too many times` (video.mp4 needs to exist):

```python
from BusinessTampereTrafficMonitoring.stream_reader.stream_reader import StreamReader
sr = StreamReader("video.mp4")
# queue is empty because we never started reading stream to buffer
sr.read_buffer_to_cache()
```

**Comment by lassijjk** [comment]
That is sort of funny since task done is in the same place as before, I'll check it out.

**Comment by Andriamanitra** [comment]
> That is sort of funny since task done is in the same place as before, I'll check it out.

There was a problem before too, but it failed even earlier because of `frame` being undefined. Best get both of the issues fixed at the same time while we are at it. :smile:

**Comment by lassijjk** [comment]
I guess this is happening because put has never been called in the first place, I'll try to investigate a bit further.

**Comment by lassijjk** [comment]
> If you try to run this piece of code you'll get `ValueError: task_done() called too many times` (video.mp4 needs to exist for the snippet to work):
> 
> ```python
> from BusinessTampereTrafficMonitoring.stream_reader.stream_reader import StreamReader
> sr = StreamReader("video.mp4")
> # queue is empty because we never started reading stream to buffer
> sr.read_buffer_to_cache()
> ```

Okay this one was a fairly small fix, committing to this pull request.

**Comment by lassijjk** [comment]
Annnnnd commiting once more.

**Pull request merged**
